config/routes.rb
Rails.application.routes.draw do

  resources :referrals do
    get '/complete', to: 'confirm_referrals#edit', on: :member
    patch '/complete', to: 'confirm_referrals#update', on: :member
  end

  resources :clients do
    get '/search', to: 'client_search#new', as: :search, on: :collection
    post '/search', to: 'client_search#create', on: :collection
  end

  resources :housing
  resources :organizations

  devise_for :users

  resources :client do
    resources :client_beds, as: :beds
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :ss_number, presence: true

  has_many :client_military_conflicts
  has_many :military_conflicts, through: :military_conflict_id
  has_many :client_ethnicities
  has_many :ethnicities, through: :client_ethnicities

  def full_name
    if middle_name.blank?
      "#{last_name}, #{first_name}"
    else
      "#{last_name}, #{first_name} #{middle_name}"
    end
  end
end

app/models/client_bed.rb
class ClientBed < ApplicationRecord
  validates :client_id, presence: true
  validates :organization_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :organization, counter_cache: :client_bed_count
end

app/models/client_ethnicity.rb
class ClientEthnicity < ApplicationRecord
  validates :client_id, presence: true
  validates :ethnicity_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :ethnicity
end

app/models/client_military_conflict.rb
class ClientMilitaryConflict < ApplicationRecord
  validates :client_id, presence: true
  validates :military_conflict_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :military_conflict
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
  validates :description, presence: true

  has_many :client_ethnicities
  has_many :clients, through: :client_ethnicities
end

app/models/military_conflict.rb
class MilitaryConflict < ApplicationRecord
  validates :description, presence: true

  has_many :client_military_conflicts
  has_many :clients, through: :client_military_conflicts
end

app/models/organization.rb
class Organization < ApplicationRecord

  def open_beds
    max_beds - client_bed_count
  end
end

app/models/organization_admin.rb
class OrganizationAdmin < ApplicationRecord
end

app/models/referral.rb
class Referral < ApplicationRecord
  validates :referred_organization_id, presence: true
  validates :referring_organization_id, presence: true
  validates :client_id, presence: true
  validates :reffered_by_id, presence: true

  belongs_to :referred_organization, class_name: Organization, foreign_key: :referred_organization_id
  belongs_to :reffering_organization, class_name: Organization, foreign_key: :referring_organization_id
  belongs_to :client
  belongs_to :user, foreign_key: :reffered_by_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.first
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find params[:id]
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find parmas[:id]
  end

  def create
    @client = Client.new client_params
    if @client.save
      redirect_to client_path(@client.id), success: 'Save Successful'
    else
      render :new
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes client_params
      redirect_to client_path(@client.id), success: 'Save Sucessful'
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find params[:id]
    @client.destroy
    redirect_to clients_path, success: 'Destroy Successful'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    organizations = Organization.where("organizations.max_beds - organizations.client_bed_count > 0").sort { |x,y| x.open_beds <=> y.open_beds }
    @organizations = organizations.first(6)
  end
end

app/controllers/housing_controller.rb
class HousingController < ApplicationController

  def index
    @organizations = Organization.all
  end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  def index
    @referrals = Referral.all
  end

  def new
    @referral = Referral.new
  end

  def create
    @referral = Referral.new referral_params
    if @referral.save
      redirect_to referrals_path, success: 'Save Successful'
    else
      render :new
    end
  end

  private

  def referral_params
    params.require(:referral).permit(:referring_organization_id, :referred_organization_id,
                                     :reffered_by_id, :client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_beds_helper.rb
module ClientBedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/housing_helper.rb
module HousingHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/clients/index.html.erb
<h2>Client List</h2>

<div class="text-right" style="margin-bottom:10px">
  <%= link_to 'Client Search', search_clients_path, class: 'btn btn-primary' %>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Birthday</th>
      <th>Social Security Number</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.full_name %></td>
        <td><%= l(client.birthday, format: :nice) if client.birthday %></td>
        <td><%= client.ss_number %></td>
        <td>
          <%= link_to 'View Profile', client_path(client.id), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clients/show.html.erb
<h2><%= @client.full_name %></h2>
<% if @client.birthday %>
  <p><em>DOB:</em> <%= l(@client.birthday, format: :nice) %></p>
<% end %>

<p><em>Social Security #:</em><%= @client.ss_number %></p>
<p><em>Veteran:</em> <%= @client.veteran %></p>

app/views/home/index.html.erb
<div class="container">
  <div class="header clearfix">
    <nav>
      <ul class="nav nav-pills pull-right">
        <li role="presentation" class="active"><%= link_to "Home", root_path  %></li>
        <li role="presentation"><%= link_to "Clients", clients_path %></li>
        <li role="presentation"><%= link_to "Organizations", organizations_path %></li>
        <li role="presentation"><%= link_to "Housing", housing_index_path %></li>
      </ul>
    </nav>
    <h3 class="text-muted">54 Characters</h3>
  </div>
  <div class="jumbotron">
    <h1>Housing Opportunities!</h1>
    <p class="lead">Learn about opportunities in STL.</p>
    <p>Contact a CoC today to get enrolled!</p>
  </div>

  <div class="row marketing">
    <% @organizations.first(6).in_groups_of(3).each do |group| %>
      <div class="col-md-12">
        <% group.each do |item| %>
          <% unless item.nil?  %>
            <%= link_to organization_path(item.id) do %>
            <div class="item well row">
              <div class="left-box col-md-4">
                <h3>Available Beds: <%= item.client_bed_count %></h3>
              </div>
              <div class="right-box col-md-8">
                <h4><%= item.organization_name %></h4>
                <p><%= item.description %></p>
              </div>
            </div>
          <% end %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <%= link_to "View All Organizations", organizations_path, style: "margin-bottom:10px;margin-top:10px", class: "btn btn-primary" %>
</div>

<footer class="footer">
  <a href="http://www.sdscomputers.com"><p>&copy; 2016 The Lunatic Nerds</p></a>
</footer>

app/views/housing/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Organization Name</th>
      <th>Bed Capacity</th>
      <th>Beds Available</th>
    </tr>
  </thead>
  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.organization_name %></td>
        <td><%= organization.max_beds %></td>
        <td><%= organization.client_bed_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>