config/routes.rb
Rails.application.routes.draw do

  resources :referrals do
    get '/complete', to: 'confirm_referrals#edit', on: :member
    patch '/complete', to: 'confirm_referrals#update', on: :member
  end

  resources :clients do
    get '/search', to: 'client_search#new', as: :search, on: :collection
    post '/search', to: 'client_search#create', on: :collection
  end

  resources :housing
  resources :organizations

  devise_for :users

  resources :client do
    resources :client_beds, as: :beds
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :ss_number, presence: true

  has_many :client_military_conflicts
  has_many :military_conflicts, through: :military_conflict_id
  has_many :client_ethnicities
  has_many :ethnicities, through: :client_ethnicities

  def full_name
    if middle_name.blank?
      "#{last_name}, #{first_name}"
    else
      "#{last_name}, #{first_name} #{middle_name}"
    end
  end
end

app/models/client_bed.rb
class ClientBed < ApplicationRecord
  validates :client_id, presence: true
  validates :organization_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :organization, counter_cache: :client_bed_count
end

app/models/client_ethnicity.rb
class ClientEthnicity < ApplicationRecord
  validates :client_id, presence: true
  validates :ethnicity_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :ethnicity
end

app/models/client_military_conflict.rb
class ClientMilitaryConflict < ApplicationRecord
  validates :client_id, presence: true
  validates :military_conflict_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :military_conflict
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
  validates :description, presence: true

  has_many :client_ethnicities
  has_many :clients, through: :client_ethnicities
end

app/models/military_conflict.rb
class MilitaryConflict < ApplicationRecord
  validates :description, presence: true

  has_many :client_military_conflicts
  has_many :clients, through: :client_military_conflicts
end

app/models/organization.rb
class Organization < ApplicationRecord

  def open_beds
    max_beds - client_bed_count
  end
end

app/models/organization_admin.rb
class OrganizationAdmin < ApplicationRecord
end

app/models/referral.rb
class Referral < ApplicationRecord
  validates :referred_organization_id, presence: true
  validates :referring_organization_id, presence: true
  validates :client_id, presence: true
  validates :reffered_by_id, presence: true

  belongs_to :referred_organization, class_name: Organization, foreign_key: :referred_organization_id
  belongs_to :reffering_organization, class_name: Organization, foreign_key: :referring_organization_id
  belongs_to :client
  belongs_to :user, foreign_key: :reffered_by_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.first
  end
end

app/controllers/client_beds_controller.rb
class ClientBedsController < ApplicationController
  before_action :set_client_bed, only: [:show, :edit, :update, :destroy]

  # GET /client_beds
  # GET /client_beds.json
  def index
    @client_beds = ClientBed.all
  end

  # GET /client_beds/1
  # GET /client_beds/1.json
  def show
  end

  # GET /client_beds/new
  def new
    @client_bed = ClientBed.new(client_id: params[:client_id])
  end

  # GET /client_beds/1/edit
  def edit
  end

  # POST /client_beds
  # POST /client_beds.json
  def create
    @client_bed = ClientBed.new(client_bed_params)

    respond_to do |format|
      if @client_bed.save
        format.html { redirect_to @client_bed, notice: 'Client bed was successfully created.' }
        format.json { render :show, status: :created, location: @client_bed }
      else
        format.html { render :new }
        format.json { render json: @client_bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /client_beds/1
  # PATCH/PUT /client_beds/1.json
  def update
    respond_to do |format|
      if @client_bed.update(client_bed_params)
        format.html { redirect_to @client_bed, notice: 'Client bed was successfully updated.' }
        format.json { render :show, status: :ok, location: @client_bed }
      else
        format.html { render :edit }
        format.json { render json: @client_bed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /client_beds/1
  # DELETE /client_beds/1.json
  def destroy
    @client_bed.destroy
    respond_to do |format|
      format.html { redirect_to client_beds_url, notice: 'Client bed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_bed
      @client_bed = ClientBed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_bed_params
      params.require(:client_bed).permit(:client_id, :organization_id)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find params[:id]
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find parmas[:id]
  end

  def create
    @client = Client.new client_params
    if @client.save
      redirect_to client_path(@client.id), success: 'Save Successful'
    else
      render :new
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes client_params
      redirect_to client_path(@client.id), success: 'Save Sucessful'
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find params[:id]
    @client.destroy
    redirect_to clients_path, success: 'Destroy Successful'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    organizations = Organization.where("organizations.max_beds - organizations.client_bed_count > 0").sort { |x,y| x.open_beds <=> y.open_beds }
    @organizations = organizations.first(6)
  end
end

app/controllers/housing_controller.rb
class HousingController < ApplicationController

  def index
    @organizations = Organization.all
  end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  def index
    @referrals = Referral.all
  end

  def new
    @referral = Referral.new
  end

  def create
    @referral = Referral.new referral_params
    if @referral.save
      redirect_to referrals_path, success: 'Save Successful'
    else
      render :new
    end
  end

  private

  def referral_params
    params.require(:referral).permit(:referring_organization_id, :referred_organization_id,
                                     :reffered_by_id, :client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_beds_helper.rb
module ClientBedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/housing_helper.rb
module HousingHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/client_beds/_form.html.erb
<%= form_for(client_bed) do |f| %>
  <% if client_bed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client_bed.errors.count, "error") %> prohibited this client_bed from being saved:</h2>

      <ul>
      <% client_bed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :client_id %>
  <%= f.collection_select :organization_id, Organization.all, :id, :organization_name, prompt: true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/client_beds/edit.html.erb
<h1>Editing Client Bed</h1>

<%= render 'form', client_bed: @client_bed %>

<%= link_to 'Show', @client_bed %> |
<%= link_to 'Back', client_beds_path %>

app/views/client_beds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Client Beds</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @client_beds.each do |client_bed| %>
      <tr>
        <td><%= link_to 'Show', client_bed %></td>
        <td><%= link_to 'Edit', edit_client_bed_path(client_bed) %></td>
        <td><%= link_to 'Destroy', client_bed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client Bed', new_client_bed_path %>

app/views/client_beds/new.html.erb
<h1>New Client Bed</h1>

<%= render 'form', client_bed: @client_bed %>

<%= link_to 'Back', client_beds_path %>

app/views/client_beds/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_client_bed_path(@client_bed) %> |
<%= link_to 'Back', client_beds_path %>

app/views/referrals/_form.html.erb
<%= form_for @referral do  |f| %>
  <%= f.hidden_field :client_id, value: params[:client_id] %>
  <%= f.hidden_field :reffered_by_id, value: current_user.id %>
  <div class="form-group">
    <%= f.label :referring_organization_id, 'Referring Organization', class: 'control-label' %>
    <%= f.collection_select :referring_organization_id, Organization.all, :id, :organization_name, {}, { class: 'form-control' } %>
  </div>
  <div class="form-group">
    <%= f.label :referred_organization_id, 'Referred Organization', class: 'control-label' %>
    <%= f.collection_select :referred_organization_id, Organization.all, :id, :organization_name, {}, { class: 'form-control' } %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/referrals/index.html.erb
<h2>Referrals</h2>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Client Name</th>
      <th>Referring Organization</th>
      <th>Referred Organization</th>
      <th>Time Ago</th>
      <th>Actions</th>
    </tr>
    <% @referrals.each do |referral| %>
      <tr>
        <td><%= referral.client.full_name %></td>
        <td><%= referral.reffering_organization.organization_name %></td>
        <td><%= referral.referred_organization.organization_name %></td>
        <td><%= time_ago_in_words(referral.created_at) %></td>
        <td>
          <%= link_to 'Complete', complete_referral_path(referral.id), class: 'btn btn-primary' %>
        </td>
      </tr>
    <% end %>
  </thead>
</table>

app/views/referrals/new.html.erb
<h2>Refer User To Organization</h2>
<%= render partial: 'form' %>