config/routes.rb
Rails.application.routes.draw do

  resources :referrals do
    get '/complete', to: 'confirm_referrals#edit', on: :member
    patch '/complete', to: 'confirm_referrals#update', on: :member
  end

  resources :clients do
    get '/search', to: 'client_search#new', as: :search, on: :collection
    post '/search', to: 'client_search#create', on: :collection
  end

  resources :housing
  resources :organizations

  devise_for :users

  resources :client do
    resources :client_beds, as: :beds
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :ss_number, presence: true

  has_many :client_military_conflicts
  has_many :military_conflicts, through: :military_conflict_id
  has_many :client_ethnicities
  has_many :ethnicities, through: :client_ethnicities

  def full_name
    if middle_name.blank?
      "#{last_name}, #{first_name}"
    else
      "#{last_name}, #{first_name} #{middle_name}"
    end
  end
end

app/models/client_bed.rb
class ClientBed < ApplicationRecord
  validates :client_id, presence: true
  validates :organization_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :organization, counter_cache: :client_bed_count
end

app/models/client_ethnicity.rb
class ClientEthnicity < ApplicationRecord
  validates :client_id, presence: true
  validates :ethnicity_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :ethnicity
end

app/models/client_military_conflict.rb
class ClientMilitaryConflict < ApplicationRecord
  validates :client_id, presence: true
  validates :military_conflict_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :military_conflict
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
  validates :description, presence: true

  has_many :client_ethnicities
  has_many :clients, through: :client_ethnicities
end

app/models/military_conflict.rb
class MilitaryConflict < ApplicationRecord
  validates :description, presence: true

  has_many :client_military_conflicts
  has_many :clients, through: :client_military_conflicts
end

app/models/organization.rb
class Organization < ApplicationRecord

  def open_beds
    max_beds - client_bed_count
  end
end

app/models/organization_admin.rb
class OrganizationAdmin < ApplicationRecord
end

app/models/referral.rb
class Referral < ApplicationRecord
  validates :referred_organization_id, presence: true
  validates :referring_organization_id, presence: true
  validates :client_id, presence: true
  validates :reffered_by_id, presence: true

  belongs_to :referred_organization, class_name: Organization, foreign_key: :referred_organization_id
  belongs_to :reffering_organization, class_name: Organization, foreign_key: :referring_organization_id
  belongs_to :client
  belongs_to :user, foreign_key: :reffered_by_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    User.first
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find params[:id]
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find parmas[:id]
  end

  def create
    @client = Client.new client_params
    if @client.save
      redirect_to client_path(@client.id), success: 'Save Successful'
    else
      render :new
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes client_params
      redirect_to client_path(@client.id), success: 'Save Sucessful'
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find params[:id]
    @client.destroy
    redirect_to clients_path, success: 'Destroy Successful'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    organizations = Organization.where("organizations.max_beds - organizations.client_bed_count > 0").sort { |x,y| x.open_beds <=> y.open_beds }
    @organizations = organizations.first(6)
  end
end

app/controllers/housing_controller.rb
class HousingController < ApplicationController

  def index
    @organizations = Organization.all
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show

  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:email, :organization_name, :address, :phone, :description, :active)
    end
end

app/controllers/referrals_controller.rb
class ReferralsController < ApplicationController
  def index
    @referrals = Referral.all
  end

  def new
    @referral = Referral.new
  end

  def create
    @referral = Referral.new referral_params
    if @referral.save
      redirect_to referrals_path, success: 'Save Successful'
    else
      render :new
    end
  end

  private

  def referral_params
    params.require(:referral).permit(:referring_organization_id, :referred_organization_id,
                                     :reffered_by_id, :client_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_beds_helper.rb
module ClientBedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/housing_helper.rb
module HousingHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/organizations/_form.html.erb
<%= form_for @organization do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :organization_name, 'Name', :class => 'control-label' %>
          <%= f.text_field :organization_name, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :description, 'Description', :class => 'control-label' %>
          <%= f.text_area :description, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :address, 'Address', :class => 'control-label' %>
          <%= f.text_field :address, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'Email', :class => 'control-label' %>
          <%= f.text_field :email, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :phone, 'Phone', :class => 'control-label' %>
          <%= f.text_field :phone, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :max_beds, 'Beds Capacity', :class => 'control-label' %>
          <%= f.text_field :max_beds, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :client_bed_count, 'Beds Available', :class => 'control-label' %>
          <%= f.text_field :client_bed_count, :class => 'tinymce form-control', :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="checkbox col-lg-12"><label><%= f.check_box :active %> Active</label></div>
      </div>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/_show.html.erb
<%= form_for @organization do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
  <% end %>
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :organization_name, 'Name', :class => 'control-label' %>
          <%= f.text_field :organization_name, :class => 'tinymce form-control', :disabled => true, :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :description, 'Description', :class => 'control-label' %>
          <%= f.text_area :description, :class => 'tinymce form-control', :disabled => true, :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :address, 'Address', :class => 'control-label' %>
          <%= f.text_field :address, :class => 'tinymce form-control', :disabled => true, :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'Email', :class => 'control-label' %>
          <%= f.text_field :email, :class => 'tinymce form-control', :disabled => true, :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :max_beds, 'Beds Capacity', :class => 'control-label' %>
          <%= f.text_field :max_beds, :class => 'tinymce form-control', :disabled => true, :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="form-group">
          <%= f.label :client_bed_count, 'Beds Available', :class => 'control-label' %>
          <%= f.text_field :client_bed_count, :class => 'tinymce form-control', :disabled => true, :autofocus => true %>
          <%= tinymce %>
        </div>
        <div class="checkbox col-lg-12"><label><%= f.check_box :active %> Active</label></div>
      </div>
    </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<% @organizations.each do |o| %>
  <div class="col-md-12">
    <div class="col-md-6" style="padding-bottom:5px"><img src="http://placehold.it/350x150"></div>
    <div class="col-md-6">
      <div class="col-md-12"><%= o.organization_name %></div>
      <hr>
      <div class="col-md-12"><%= o.description %></div>
    </div>
  </div>
  <div class="col-md-12 text-right">
    <%= link_to 'Show', o, class: "btn" %>
    <%= link_to 'Edit', edit_organization_path(o), class: "btn" %>
    <%= link_to 'Destroy', o, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn" %>
  </div>
<% end %>


<br>

<%= link_to 'New Organization', new_organization_path, class: "btn btn-primary" %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<h1>Viewing Organization</h1>

<%= render 'show', organization: @organization %>

<%= link_to 'Edit', edit_organization_path, class: "btn" %>
<%= link_to 'Back', organizations_path, class: "btn" %>