config/routes.rb
Rails.application.routes.draw do

  resources :referrals do
    get '/complete', to: 'confirm_referrals#edit', on: :member
    patch '/complete', to: 'confirm_referrals#update', on: :member
  end

  resources :clients do
    get '/search', to: 'client_search#new', as: :search, on: :collection
    post '/search', to: 'client_search#create', on: :collection
  end

  resources :housing
  resources :organizations

  devise_for :users

  resources :client do
    resources :client_beds, as: :beds
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birthday, presence: true
  validates :ss_number, presence: true

  has_many :client_military_conflicts
  has_many :military_conflicts, through: :military_conflict_id
  has_many :client_ethnicities
  has_many :ethnicities, through: :client_ethnicities

  def full_name
    if middle_name.blank?
      "#{last_name}, #{first_name}"
    else
      "#{last_name}, #{first_name} #{middle_name}"
    end
  end
end

app/models/client_bed.rb
class ClientBed < ApplicationRecord
  validates :client_id, presence: true
  validates :organization_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :organization, counter_cache: :client_bed_count
end

app/models/client_ethnicity.rb
class ClientEthnicity < ApplicationRecord
  validates :client_id, presence: true
  validates :ethnicity_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :ethnicity
end

app/models/client_military_conflict.rb
class ClientMilitaryConflict < ApplicationRecord
  validates :client_id, presence: true
  validates :military_conflict_id, presence: true, uniqueness: { scope: :client_id }

  belongs_to :client
  belongs_to :military_conflict
end

app/models/ethnicity.rb
class Ethnicity < ApplicationRecord
  validates :description, presence: true

  has_many :client_ethnicities
  has_many :clients, through: :client_ethnicities
end

app/models/military_conflict.rb
class MilitaryConflict < ApplicationRecord
  validates :description, presence: true

  has_many :client_military_conflicts
  has_many :clients, through: :client_military_conflicts
end

app/models/organization.rb
class Organization < ApplicationRecord

  def open_beds
    max_beds - client_bed_count
  end
end

app/models/organization_admin.rb
class OrganizationAdmin < ApplicationRecord
end

app/models/referral.rb
class Referral < ApplicationRecord
  validates :referred_organization_id, presence: true
  validates :referring_organization_id, presence: true
  validates :client_id, presence: true
  validates :reffered_by_id, presence: true

  belongs_to :referred_organization, class_name: Organization, foreign_key: :referred_organization_id
  belongs_to :reffering_organization, class_name: Organization, foreign_key: :referring_organization_id
  belongs_to :client
  belongs_to :user, foreign_key: :reffered_by_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    @clients = Client.all
  end

  def show
    @client = Client.find params[:id]
  end

  def new
    @client = Client.new
  end

  def edit
    @client = Client.find parmas[:id]
  end

  def create
    @client = Client.new client_params
    if @client.save
      redirect_to client_path(@client.id), success: 'Save Successful'
    else
      render :new
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update_attributes client_params
      redirect_to client_path(@client.id), success: 'Save Sucessful'
    else
      render :edit
    end
  end

  def destroy
    @client = Client.find params[:id]
    @client.destroy
    redirect_to clients_path, success: 'Destroy Successful'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    organizations = Organization.where("organizations.max_beds - organizations.client_bed_count > 0").sort { |x,y| x.open_beds <=> y.open_beds }
    @organizations = organizations.first(6)
  end
end

app/controllers/housing_controller.rb
class HousingController < ApplicationController

  def index
    @organizations = Organization.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_beds_helper.rb
module ClientBedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/housing_helper.rb
module HousingHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/referrals_helper.rb
module ReferralsHelper
end

app/views/layouts/_main_menu.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "52 Characters", root_path, class: 'navbar-brand'  %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li role="presentation" class="active"><%= link_to "Home", root_path  %></li>
        <li role="presentation"><%= link_to "Clients", clients_path %></li>
        <li role="presentation"><%= link_to "Organizations", organizations_path %></li>
        <li role="presentation"><%= link_to "Housing", housing_index_path %></li>
        <li role="presentation"><%= link_to "Referrals", referrals_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Globalhack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/main_menu' unless current_page?(root_path) %>
    <div class="container-fluid main-content">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>